apiVersion: v1
kind: Secret
metadata:
  name: git-auth
  namespace: cicd
  annotations:
    tekton.dev/git-0: https://github.com/
type: kubernetes.io/basic-auth
stringData:
  username: tekton
  password: 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
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: git-push-service-account
  namespace: cicd
secrets:
  - name: git-auth
